<?php
// ============================================================
// ARTICLE HTML SANITIZER (IMP-006 / SEC-05)
// Server-side authoritative HTML sanitization for article content.
//
// Enforces a strict element and attribute allowlist, normalizes
// safe legacy editor tags (b -> strong, i -> em, div -> p),
// validates URLs against dangerous schemes (javascript:, data:, vbscript:, //),
// enforces rel="noopener noreferrer" on target="_blank",
// and prunes all dangerous tags (script, style, iframe, svg, form, etc.).
// ============================================================

class ArticleHtmlSanitizer {

    /**
     * Allowed HTML elements (lowercase)
     */
    private const ALLOWED_ELEMENTS = [
        'p',
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'ul', 'ol', 'li',
        'strong', 'em',
        'blockquote',
        'a',
        'img',
        'br',
        'mark',
    ];

    /**
     * Block-level tags for checking div conversion/unwrapping
     */
    private const BLOCK_TAGS = [
        'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'ul', 'ol', 'blockquote', 'div',
    ];

    /**
     * Dangerous tags pruned along with all their children
     */
    private const PRUNED_TAGS = [
        'script', 'style', 'iframe', 'object', 'embed',
        'svg', 'canvas', 'video', 'audio', 'applet',
        'form', 'input', 'textarea', 'button', 'select', 'option',
        'meta', 'link', 'base', 'frame', 'frameset',
    ];

    /**
     * Allowed attributes per element (lowercase tag => list of allowed lowercase attrs)
     */
    private const ALLOWED_ATTRIBUTES = [
        'a'          => ['href', 'target', 'rel', 'title'],
        'img'        => ['src', 'alt', 'class'],
        'mark'       => ['class'],
        'p'          => ['dir'],
        'blockquote' => ['dir'],
        'h1'         => ['dir'],
        'h2'         => ['dir'],
        'h3'         => ['dir'],
        'h4'         => ['dir'],
        'h5'         => ['dir'],
        'h6'         => ['dir'],
        'ul'         => ['dir'],
        'ol'         => ['dir'],
        'li'         => ['dir'],
    ];

    /**
     * Whitelist of safe CSS classes for elements that permit class
     */
    private const ALLOWED_CLASSES = [
        'img'  => ['article-image', 'article-image-small', 'article-image-large'],
        'mark' => ['text-highlight'],
    ];

    /**
     * Whitelist of allowed protocols for hyperlinks
     */
    private const ALLOWED_HREF_PROTOCOLS = ['http', 'https', 'mailto'];

    /**
     * Whitelist of allowed protocols for images
     */
    private const ALLOWED_IMG_PROTOCOLS = ['http', 'https'];

    /**
     * Sanitize article HTML content.
     *
     * @param string|null $dirtyHtml Raw HTML input from editor
     * @return string Sanitized HTML safe for storage and rendering
     */
    public static function sanitize(?string $dirtyHtml): string {
        if ($dirtyHtml === null) {
            return '';
        }

        $trimmed = trim($dirtyHtml);
        if ($trimmed === '') {
            return '';
        }

        $doc = new DOMDocument();
        libxml_use_internal_errors(true);

        // Load with explicit UTF-8 meta in body wrapper
        $wrapped = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>' . $trimmed . '</body></html>';
        $doc->loadHTML($wrapped, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        libxml_clear_errors();

        $body = $doc->getElementsByTagName('body')->item(0);
        if (!$body) {
            return '';
        }

        // Pass 1: Normalize legacy tags (div -> p / unwrap, b -> strong, i -> em)
        self::normalizeLegacyTags($body, $doc);

        // Pass 2: Clean nodes recursively against element & attribute allowlists
        self::cleanNode($body, $doc);

        // Serialize output
        $cleanHtml = '';
        foreach ($body->childNodes as $child) {
            $cleanHtml .= $doc->saveHTML($child);
        }

        return trim($cleanHtml);
    }

    /**
     * Pass 1: Normalizes legacy tags generated by contenteditable or pasted text.
     * b -> strong, i -> em, div -> p (or unwrap if containing block children).
     */
    private static function normalizeLegacyTags(DOMNode $node, DOMDocument $doc): void {
        // Collect all div, b, and i elements in document
        $divs = iterator_to_array($doc->getElementsByTagName('div'));
        foreach (array_reverse($divs) as $div) {
            if (!$div->parentNode) {
                continue;
            }

            // Check if this div contains block children
            if (self::hasBlockChildren($div)) {
                // Unwrap outer div
                while ($div->firstChild) {
                    $div->parentNode->insertBefore($div->firstChild, $div);
                }
                $div->parentNode->removeChild($div);
            } else {
                // Convert to <p>
                $p = $doc->createElement('p');
                // Preserve allowed dir attribute if present
                if ($div->hasAttribute('dir')) {
                    $p->setAttribute('dir', $div->getAttribute('dir'));
                }
                while ($div->firstChild) {
                    $p->appendChild($div->firstChild);
                }
                $div->parentNode->replaceChild($p, $div);
            }
        }

        // b -> strong
        $bElements = iterator_to_array($doc->getElementsByTagName('b'));
        foreach (array_reverse($bElements) as $b) {
            if (!$b->parentNode) continue;
            $strong = $doc->createElement('strong');
            while ($b->firstChild) {
                $strong->appendChild($b->firstChild);
            }
            $b->parentNode->replaceChild($strong, $b);
        }

        // i -> em
        $iElements = iterator_to_array($doc->getElementsByTagName('i'));
        foreach (array_reverse($iElements) as $i) {
            if (!$i->parentNode) continue;
            $em = $doc->createElement('em');
            while ($i->firstChild) {
                $em->appendChild($i->firstChild);
            }
            $i->parentNode->replaceChild($em, $i);
        }
    }

    /**
     * Determines if a DOMNode contains any block-level element children.
     */
    private static function hasBlockChildren(DOMNode $node): bool {
        foreach ($node->childNodes as $child) {
            if ($child->nodeType === XML_ELEMENT_NODE && in_array(strtolower($child->nodeName), self::BLOCK_TAGS, true)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Pass 2: Recursively cleans nodes against element and attribute allowlists.
     */
    private static function cleanNode(DOMNode $node, DOMDocument $doc): void {
        for ($i = $node->childNodes->length - 1; $i >= 0; $i--) {
            $child = $node->childNodes->item($i);
            if (!$child) {
                continue;
            }

            if ($child->nodeType === XML_ELEMENT_NODE) {
                $tag = strtolower($child->nodeName);

                // Prune dangerous tags completely along with their children
                if (in_array($tag, self::PRUNED_TAGS, true)) {
                    $node->removeChild($child);
                    continue;
                }

                // If not in element allowlist, unwrap children (preserve inner text)
                if (!in_array($tag, self::ALLOWED_ELEMENTS, true)) {
                    while ($child->firstChild) {
                        $node->insertBefore($child->firstChild, $child);
                    }
                    $node->removeChild($child);
                    continue;
                }

                // Clean attributes on allowed element
                if ($child instanceof DOMElement) {
                    self::cleanAttributes($child, $tag);
                }

                // If an <img> was removed inside cleanAttributes (e.g. invalid src), skip recursion
                if (!$child->parentNode) {
                    continue;
                }

                // Recurse into child elements
                self::cleanNode($child, $doc);

            } elseif ($child->nodeType === XML_COMMENT_NODE) {
                // Strip HTML comments
                $node->removeChild($child);
            } elseif ($child->nodeType !== XML_TEXT_NODE) {
                // Remove processing instructions, entity references, CDATA, etc.
                $node->removeChild($child);
            }
        }
    }

    /**
     * Sanitizes attributes on a single DOMElement.
     */
    private static function cleanAttributes(DOMElement $element, string $tag): void {
        $allowedAttrs = self::ALLOWED_ATTRIBUTES[$tag] ?? [];

        $toRemove = [];
        foreach ($element->attributes as $attr) {
            $attrName = strtolower($attr->name);

            // Strip event handlers (on*) and inline styles
            if (str_starts_with($attrName, 'on') || $attrName === 'style' || !in_array($attrName, $allowedAttrs, true)) {
                $toRemove[] = $attr->name;
                continue;
            }

            // URL Validation on href
            if ($attrName === 'href') {
                if (!self::isSafeUrl($attr->value, false)) {
                    $toRemove[] = $attr->name;
                    continue;
                }
            }

            // URL Validation on src (images)
            if ($attrName === 'src') {
                if (!self::isSafeUrl($attr->value, true)) {
                    $toRemove[] = $attr->name;
                    continue;
                }
            }

            // Class whitelist enforcement
            if ($attrName === 'class') {
                $allowedClasses = self::ALLOWED_CLASSES[$tag] ?? [];
                $classes = preg_split('/\s+/', trim($attr->value));
                $validClasses = array_intersect($classes, $allowedClasses);
                if (empty($validClasses)) {
                    $toRemove[] = $attr->name;
                } else {
                    $element->setAttribute('class', implode(' ', $validClasses));
                }
            }

            // Direction attribute whitelist enforcement
            if ($attrName === 'dir') {
                $dirVal = strtolower(trim($attr->value));
                if (!in_array($dirVal, ['rtl', 'ltr', 'auto'], true)) {
                    $toRemove[] = $attr->name;
                } else {
                    $element->setAttribute('dir', $dirVal);
                }
            }

            // Target attribute enforcement on <a>
            if ($tag === 'a' && $attrName === 'target') {
                $targetVal = strtolower(trim($attr->value));
                if ($targetVal === '_blank') {
                    $element->setAttribute('target', '_blank');
                    $element->setAttribute('rel', 'noopener noreferrer');
                } else {
                    $toRemove[] = $attr->name;
                }
            }
        }

        foreach ($toRemove as $name) {
            $element->removeAttribute($name);
        }

        // Target blank safety: if target is _blank, guarantee rel="noopener noreferrer"
        if ($tag === 'a' && strtolower($element->getAttribute('target')) === '_blank') {
            $element->setAttribute('rel', 'noopener noreferrer');
        }

        // If an <img> has no src or empty src after attribute cleaning, remove the img element
        if ($tag === 'img') {
            $src = trim($element->getAttribute('src'));
            if ($src === '') {
                $element->parentNode->removeChild($element);
            }
        }
    }

    /**
     * Strict URL scheme and structure validation.
     *
     * @param string $url The URL to validate
     * @param bool $isImage True if validating an <img> src, false for <a> href
     * @return bool True if safe, false if dangerous
     */
    public static function isSafeUrl(string $url, bool $isImage = false): bool {
        $trimmed = trim($url);
        if ($trimmed === '') {
            return false;
        }

        // Reject protocol-relative URLs (//evil.example)
        if (str_starts_with($trimmed, '//')) {
            return false;
        }

        // Reject control characters, non-printables, and null bytes
        if (preg_match('/[\x00-\x1f\x7f]/', $trimmed)) {
            return false;
        }

        // Allow legitimate relative paths starting with '/' or '#'
        if ($trimmed[0] === '/' || $trimmed[0] === '#') {
            return true;
        }

        // Strip internal whitespace/control chars to neutralize obfuscations (e.g. jav\tascript:)
        $normalized = preg_replace('/[\x00-\x20\x7f\s]+/u', '', $trimmed);

        // Check for scheme presence before path/query/fragment delimiters
        if (str_contains($normalized, ':')) {
            $colonPos = strpos($normalized, ':');
            $slashPos = strpos($normalized, '/');
            $questionPos = strpos($normalized, '?');
            $hashPos = strpos($normalized, '#');

            $firstDelimiter = PHP_INT_MAX;
            if ($slashPos !== false) $firstDelimiter = min($firstDelimiter, $slashPos);
            if ($questionPos !== false) $firstDelimiter = min($firstDelimiter, $questionPos);
            if ($hashPos !== false) $firstDelimiter = min($firstDelimiter, $hashPos);

            if ($colonPos < $firstDelimiter) {
                $scheme = strtolower(substr($normalized, 0, $colonPos));
                $allowedSchemes = $isImage ? self::ALLOWED_IMG_PROTOCOLS : self::ALLOWED_HREF_PROTOCOLS;
                return in_array($scheme, $allowedSchemes, true);
            }
        }

        // Relative path without leading slash (e.g. "article.html")
        return true;
    }
}
